version: '3.9'

services:

  analyzer:
    build: ./analyzer
    ports:
      - "8001:8001"

  producer:
    build: ./producer
    depends_on:
      - analyzer

  frontend:
    build: ./frontend
    ports:
      - "8501:8501"
    depends_on:
      - analyzer